# Generated by Django 4.2.5 on 2024-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_text',
            new_name='notice_title',
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.CharField(default='Description', max_length=2000),
            preserve_default=False,
        ),
    ]
